model:
    arch: hardnet
data:
    dataset: base_cityscapes_convention
    version: scooter_halflabelled
    train_split: train
    val_split: val
    img_rows: 513 #1024
    img_cols: 513 #1024
    path: D:/data/
    sbd_path: /mnt/ssd2/Cityscapes/
training:
    train_iters: 500
    batch_size: 4
    val_interval: 50
    n_workers: 4
    print_interval: 10
    augmentations:
        hflip: 0.5
        rscale_crop: [1024, 1024]
    optimizer:
        name: 'sgd'
        lr: 0.002
        weight_decay: 0.0005
        momentum: 0.9
    seg_loss:
        name: 'bootstrapped_cross_entropy'
        min_K: 4096
        loss_th: 0.3
        size_average: True
    lr_schedule: 
        name: 'poly_lr'
        max_iter: 500
    resume: D:/Documents/fchardnet/weights/hardnet70_cityscapes_model.pkl
    finetune: None
    save_metric: "Mean IoU : \t" # "Mean IoU : \t" for seg, "Overall Accuracy: \t" for classifier
